import { FC } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import img from '../public/images/404.png';
import arrow from '../public/arrow.svg';

import { SectionTitle } from "@/components/section-title/section-title";
import { Footer } from "@/components/footer/footer";

import styles from '../scss/_error.module.scss';

interface NewsProps {
    
}

const News: FC<NewsProps> = () => {

    return ( 
        <>
            <Head>
                <title>404</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.inner}>
               <SectionTitle title='Страница не найдена' color='black'/>

                <Image src={img} width={491} height={454} alt="404" className={styles.image}/>

                <Link href="/" className={styles.link}>
                    <span className={styles.text}>
                        Вернуться на главную
                    </span>
                    <Image src={arrow} width={20} height={20} alt="arrow" className={styles.arrow}/>
                    
                </Link>
            </div>

            <Footer form={'disable'}/>
        </>
    );
};

export default News;