import { FC } from "react";
import Head from "next/head";

import { CareerTopSection } from "@/components/Career/careerTopSection/careerTopSection";
import { ItemsList } from "@/components/Event/itemsList/itemsList";
import { Partners } from "@/components/partners/partners";
import { Peoples } from "@/components/sections/peoples/peoples";
import { Reviews } from "@/components/reviews/reviews";
import { CardItems } from "@/components/sections/cardItems/cardItems";
import { WorkStats } from "@/components/Career/workStats/workStars";
import { YourPath } from "@/components/Career/yourPath/yourPath";
import { Vacancy } from "@/components/Career/vacancy/vacancy";
import { Footer } from "@/components/footer/footer";


import styles from '../scss/career.module.scss';


interface CareerProps {
    
}
 
const Career: FC<CareerProps> = () => {
    return (  
        <>
            <Head>
                <title>Career</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <CareerTopSection/>
            <ItemsList/>
            <WorkStats/>
            <YourPath/>
            <Vacancy/>
            <Partners title='Компании где работают уже наши студенты'/>
            <Peoples content={Reviews} title="Истории успеха"/>
            <CardItems title="Помогаем с трудоустройствовом" bottom={true}/>
            
            <Footer/>
        </>
    );
}
 
export default Career;