import { FC } from "react";
import Head from "next/head";

import { TopSection } from "@/components/Career/topSection/topSection";
import { ItemsList } from "@/components/Event/itemsList/itemsList";
import { Partners } from "@/components/partners/partners";
import { Peoples } from "@/components/sections/peoples/peoples";
import { Reviews } from "@/components/reviews/reviews";
import { Footer } from "@/components/footer/footer";


import styles from '../scss/career.module.scss';


interface CareerProps {
    
}
 
const Career: FC<CareerProps> = () => {
    return (  
        <>
            <Head>
                <title>Career</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <TopSection/>
            <ItemsList/>

            <Partners title='Компании, где работают наши студенты'/>
            <Peoples content={Reviews} title="Истории успеха"/>
            {/* <Footer/> */}
        </>
    );
}
 
export default Career;