import { FC } from "react";
import Head from "next/head";
import Image from "next/image";
import cl from "classnames";
import Link from "next/link";
import { YMaps, Map, Placemark } from '@pbe/react-yandex-maps';

import telephone from "../public/contacts-icons/telephone.svg";
import mail from "../public/contacts-icons/mail.svg";
import location from "../public/contacts-icons/location.svg";

import vk from "../public/contacts-icons/vk.svg";
import insta from "../public/contacts-icons/insta.svg";
import facebook from "../public/contacts-icons/facebook.svg";
import youtube from "../public/contacts-icons/youtube.svg";
import telegram from "../public/contacts-icons/telegram.svg";
import yandex from "../public/contacts-icons/yandex.svg";

import { Pagination } from "@/components/pagination/pagination";
import { SectionTitle } from "@/components/section-title/section-title";
import { Footer } from "@/components/footer/footer";

import styles from "../scss/contacts.module.scss";

interface ContactsProps {}

const links = [
    {
        img: vk,
        link: '#',
    },
    {
        img: insta,
        link: '#',
    },
    {
        img: facebook,
        link: '#',
    },
    {
        img: youtube,
        link: '#',
    },
    {
        img: telegram,
        link: '#',
    },
]

const Contacts: FC<ContactsProps> = () => {
    return (
        <>
            <Head>
                <title>Our Contacts</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.inner}>
                <div className="container">
                    <Pagination page="Контакты" link="/contacts" />
                    <SectionTitle title="Контакты" color="black" />
                    <div className={styles.content}>
                        <div className={styles.contacts}>
                            <div className={styles.items}>
                                <div className={styles.item}>
                                    <Image
                                        src={telephone}
                                        width={16}
                                        height={24}
                                        alt="icon"
                                        className={styles.img}
                                    />
                                    <Link
                                        className={styles.telephone}
                                        href="tel:8 800 950-33-98 "
                                    >
                                        8 800 950-33-98
                                    </Link>
                                </div>
                                <div className={styles.item}>
                                    <Image
                                        src={mail}
                                        width={16}
                                        height={24}
                                        alt="icon"
                                        className={styles.img}
                                    />
                                    <Link
                                        className={styles.mail}
                                        href="mailto:info@hodfutureacademy.ru"
                                    >
                                        info@hodfutureacademy.ru
                                    </Link>
                                </div>
                                <div className={styles.item}>
                                    <Image
                                        src={location}
                                        width={16}
                                        height={24}
                                        alt="icon"
                                        className={styles.img}
                                    />
                                    <span className={styles.adress}>
                                        г. Москва, ул. Ленина, д. 50
                                    </span>
                                </div>
                            </div>

                            <div className={styles.links}>
                                {links.map((link,i) =>
                                    <Link key={i} className={styles.link} href={link.link}>
                                        <Image src={link.img} width={22} height={22} alt='social-link'/>
                                    </Link>
                                )}
                            </div>

                            <Link className={styles.yandex_link} href='#'>
                                <Image src={yandex} width={126} height={34} alt='yandex-link'/>
                            </Link>
                        </div>
                        <YMaps>
                            <div className={styles.map}> 
                                <Map defaultState={{ center: [52.765650, 41.400728111], zoom: 16 }} width={880} height={410}>
                                    <Placemark geometry={[52.765650, 41.400728]} />
                                </Map>
                            </div>
                        </YMaps>
                    </div>
                </div>
            </div>
            <Footer />
        </>
    );
};

export default Contacts;
