import Head from 'next/head';
import { Choise } from '../components/sections/choise/choise';


const Сourses = () => {
    return (
        <>
        <Head>
        <title>Our courses</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
            <Choise/>
            <Choise/>
            <Choise/>
            <Choise/>
            <Choise/>
        </>
    );
};
export default Сourses;