import { FC } from "react";
import Head from "next/head";
import Image from "next/image";
import cl from "classnames";

import top_img from '../public/images/eventBG.jpg'

import { TopSection } from '../components/sections/topSection/topSection';
import { EventContent } from '../components/Event/eventContent/eventContent';
import { ItemsList } from "@/components/Event/itemsList/itemsList";

import { Footer } from "@/components/footer/footer";

import styles from '../scss/event.module.scss';

interface EventProps {
    
}



const Event: FC<EventProps> = () => {

    return ( 
        <>
            <Head>
                <title>Academy Event</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <TopSection content={EventContent} img={top_img}/>
            <ItemsList/>
        </>
    );
};

export default Event;
 