import Head from 'next/head'
import { Header } from '../components/header/header';
import { Footer } from '../components/footer/footer';
import { Main } from './main'
import styles from '../scss/index.module.scss';



export default function Home() {
  return (
    <>
      <Head>
        <title>Future Academy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
        <main className={styles.main}>
         <Main/>
        </main>
      <Footer/>
    </>
  )
}
