import { FC } from "react";
import Head from "next/head";
import Image from "next/image";
import cl from "classnames";


import { Footer } from "@/components/footer/footer";

import styles from '../scss/news.module.scss';

interface NewsProps {
    
}

const News: FC<NewsProps> = () => {

    return ( 
        <>
            <Head>
                <title>Our News</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            

            {/* <Footer/> */}
        </>
    );
};

export default News;