import { FC } from "react";
import Head from "next/head";
import Image from "next/image";

import { Pagination } from "@/components/pagination/pagination";
import { SectionTitle } from "@/components/section-title/section-title";
import { NewsItems } from "@/components/News/newsItems/newsItems";
import { Footer } from "@/components/footer/footer";

import styles from '../scss/news.module.scss';

interface NewsProps {
    
}

const News: FC<NewsProps> = () => {

    return ( 
        <>
            <Head>
                <title>Our News</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

                <div className='container'>
                    <div className={styles.inner}>
                        <Pagination page='Новости' link='/news'/>
                        <SectionTitle title='Новости ХОД Future Academy' color='black'/>
                        <NewsItems/>
                    </div>
                </div>

            <Footer/>
        </>
    );
};

export default News;